#!/usr/bin/env python
import sys, os

if len(sys.argv) != 3:
    print("./qdelrange [start QID] [end QID]")

sQID = int(sys.argv[1])
eQID = int(sys.argv[2])

for qid in range(sQID, eQID+1):
    os.system("qdel {0:d} &".format(qid))
