#!/bin/csh
regrun -product zebu -log /remote/vgscratch8/chenc/reg/ -diff_file /remote/vgscratch8/chenc/reg/diffs -use_stream_config TD.ZEBU


# run failure list from previous run
#regrun -product zebu -log /remote/vgscratch8/chenc/reg/ -f r_......../tmp/failure_list

